### ISSUE TITLE
Twitch messages not being read properly

### ISSUE THREAD

**Issue by xxandeer** [wAIfu-DEV/w-AI-fu#1]
It does not fetch messages from twitch, do you have any solution for that?

**Comment by wAIfu-DEV** [comment]
This part is very much not documented, my bad.

Let me give you a checklist of things to do in order to make it work:

- go to this site to get a twitch oauth token: https://twitchapps.com/tmi/
- put the token (without the 'oauth:' part i don't remember if it is included or not) inside of auth/twitch_oauth.txt
- In config.json change the value of 'twitch_channel_name' to the one you want to get the messages from (for ex: if my channel is 'https://www.twitch.tv/w_ai_fu_dev' then the value should be 'w_ai_fu_dev')
- change the value of 'read_live_chat' to true

If it still does not work, please hmu.
I will check on my end if there is anything wrong with the program itself I haven't checked in a while.

**Comment by wAIfu-DEV** [comment]
Yep there does seem to be a bug, working on it.
Also need to point out that it won't read any chat message until the user made an input (text or voice).

**Comment by xxandeer** [comment]
And also it seems like the /run command not runs when read_live_chat = true
I manage to start it by this curl command in a separate terminal
curl -X POST -H "Content-Type: application/json" -d "{\"data\": [\"channelname\"]}" http://localhost:7830/run

And I can see the the last message in localhost:7830/api in the browser

But it just loops empty message, i think that has to do with the verifyTexts booleen.

Do you have discord by any chance? We can try too figure it out together :)

**Comment by wAIfu-DEV** [comment]
Issue should be fixed now.
There was a problem with a check that was always false preventing the /run from running + some other bugs I introduced by rewriting the input system.

Download the release 1.0.3 and you are good to go!

If you still want to contact me via discord: w-AI-fu_dev#0678
