### ISSUE TITLE
no such file or directory, open './devices/devices.json'

### ISSUE THREAD

**Issue by Linuxfy** [wAIfu-DEV/w-AI-fu#18]
How to fix this error?

w-AI-fu 1.2.2
Loading config informations ...
Loading character "Hilda" ...
Loading filter ...
Getting audio devices ...
node:fs:601
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open './devices/devices.json'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at getDevices (C:\Users\LINUXFY\Downloads\w-AI-fu main\w-AI-fu\app.js:1197:21)
    at init (C:\Users\LINUXFY\Downloads\w-AI-fu main\w-AI-fu\app.js:356:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (C:\Users\LINUXFY\Downloads\w-AI-fu main\w-AI-fu\app.js:258:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: './devices/devices.json'
}

Node.js v18.16.0
Press any key to continue . . .

**Comment by wAIfu-DEV** [comment]
Hey, you might not have seen the response to your comment so here:
"Can you try running the python script at: 'w-AI-fu\devices\audio_devices.py' ? It's the script responsible for generating  './devices/devices.json' so if it didn't work it should give you an error."

Some reasons why this issue might be happening:
- Python not installed
- Missing 'python' environment variable
- Missing python dependency (should be fixed by running INSTALL.bat)
- Bug in the script

Best way to now for sure is to run the script to know if it errors or not

**Comment by Linuxfy** [comment]
i run  'w-AI-fu\devices\audio_devices.py' and devices.json appear then i run Run w-AI-fu.shortcut got same error "./devices/devices.json" is now missing from "w-AI-fu\devices" folder.

i run Python 3.10 and Node.js v18.16.

**Comment by wAIfu-DEV** [comment]
I managed to replicate the issue by removing the system environment variables for Python.
The fastest way to solve this is to reinstall Python with "Add Python 3.10 to PATH" ticked.

**Comment by wAIfu-DEV** [comment]
Did it solve your issue?

**Comment by wAIfu-DEV** [comment]
I added a more detailed error message for this case:
"Critical Error: Could not create a Python child process. This may be due to a missing Python installation, or a missing PATH system environment variable; Either can be fixed by (re)installing Python with the "Add Python 3.10 to PATH" enabled."

Please reopen the issue if it didn't solve it for you.

**Comment by Linuxfy** [comment]
yes it work. thanks you
