### ISSUE TITLE
Chat reply picking strategy

### ISSUE THREAD

**Issue by rpfilomeno** [wAIfu-DEV/w-AI-fu#37]
If there's a lot of chat messages, allow adjustments on who gets a reply  (or else the bot will make a very long queue of for replies).

Rule 1. Toggle  Prioritize by roles:  VIP > Donator/Bits > Subscribers by tier >  Followers > Regular > First time. Use weighted random choice further configurable in config.json, in python its looks like this:  https://www.geeksforgeeks.org/how-to-get-weighted-random-choice-in-python/

Rule 2. Toggle Prioritize by chat frequency/scoreboard: after applying Rule 1, pick the user who was last replied to by the bot based on the scoreboard.

Rule 3. Toggle Prioritize Questions: after evaluating Rule 1-2, give weight to picking chat messages that are classified as questions. see: https://github.com/huggingface/node-question-answering, alternatively when using scoreboards - penalize users spamming with emotes.

**Comment by wAIfu-DEV** [comment]
I agree that a way to change the chat replay policy would be a great addition.
However from what I have read the only roles I could fetch using the API would be Subscriber and Follower. https://discuss.dev.twitch.tv/t/how-to-check-all-the-chats-i-am-vip-in/23543
As to the rule 3, penalizing emote usage would require the application to know in advance what emotes are available on the channel as I don't want the user to have to keep tabs on what string of text counts as emotes. I am not aware if platforms like 7TV provide an API for that, but even they would it would force users to use that platform instead of another which is not something I want.
Still, weighting the chat messages is something that I plan on adding to w-AI-fu even if it might be different in terms of logic.
I'll leave this issue open for more suggestions

**Comment by rpfilomeno** [comment]
n terms of identifying VIPs / etc I was actually parsing badges, sorry I'm not good at nodejs I'm using Python :3 Something similar to this might exist in nodejs: https://twitchio.dev/en/latest/reference.html#chatbadge.

I'm purely using a scoreboard strategy to score users, it's similar to mIRCStats' noisiest, shortest stats, hope this gives you inspiration

**Comment by wAIfu-DEV** [comment]
I see, I was not aware of that. It seems that to using the API you need to do a [specific request](https://dev.twitch.tv/docs/irc/tags/) to get badges with each messages, so it should be able to be done.
