### ISSUE TITLE
AssignProcessToJobObject: (87) The parameter is incorrect

### ISSUE THREAD

**Issue by NezhaTheMyth** [wAIfu-DEV/w-AI-fu#40]
I get this error whenever I run the shortcut. Then once it is launched a browser pops up saying it couldn't reach the application. And i launched it using administrator privileges and it says it cant find app.js

**Comment by wAIfu-DEV** [comment]
Hi, this is an issue that seems to be linked to nodejs, there currently does not seem to be a way to fix it.
Another user who encountered the issue was able to fix it by running the application twice: [https://github.com/wAIfu-DEV/w-AI-fu/issues/25](https://github.com/wAIfu-DEV/w-AI-fu/issues/25)
If the issue persists, I would recommend using [wAIfu v2](https://github.com/wAIfu-DEV/w-AI-fu_v2) it is still in "beta" but it is proving more reliable and stable than the v1.

Hope this helps.
